[profile.default]
src = 'src'
test = 'test'
out = 'out'
libs = ['lib']
script = 'scripts'
solc_version = '0.8.19'
evm_version = 'shanghai'
extra_output = [
  "abi",
  "evm.bytecode",
  "evm.deployedBytecode",
  "evm.methodIdentifiers",
]
optimizer = true
optimizer_runs = 20_000
force = false
# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
mainnet = "https://rpc.ankr.com/eth"

[profile.SMT.model_checker]
contracts = { }
engine = 'chc'
solvers = ['z3']
show_unproved = true
timeout = 0
targets = [
  'assert',
  'constantCondition',
  'divByZero',
  'outOfBounds',
  'overflow',
  'popEmptyArray',
  'underflow',
  'balance',
]

[profile.docs]
src = 'src/dollar'

[profile.intense.fuzz]
runs = 16500000   # 5h 30m
max_test_rejects = 144000000

[profile.intense.invariant]
runs = 350000     # 5h 40m